### PR TITLE
added_class_zoom_and_wipe

### PR DESCRIPTION
**Pull request by indra057**
#i have created the classes wipe and zoom but i am 100 percent sure that its wrong also i didnt called the clases so plzz see my code and tell me where to change and what are the thinks i should do to fix the code it will be of great help to me if u would allow me to work with it so that i can learn

## Check List (Check all the applicable boxes)

- [ ] I understand that my contributions needs to pass the checks.
- [ ] If I created new functions / methods, I documented them and add type hints.
- [ ] If I modified already existing code, I updated the documentation accordingly.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by jeertmans** [comment]
Thanks for your PR @indra057!

I will review this later next week, but you can already take a look at the different checks and read why they fail: you should be able to pass all checks :-)

An error I see is that your implementation imports from `manim`, but will fail with code from `manimlib`.

If you can, you should run `pre-commit run --all-files` locally to format the files (`pip install pre-commit` is needed).

**Comment by jeertmans** [comment]
Any update @indra057?

**Comment by indra057** [comment]
sorry sir i dont now how to fix it ...as my test is failing...can u guide me with little help or with some previous pr so that i can look and try to fix issue

**Comment by jeertmans** [comment]
Did you have a look at the code from Manim?
For example, this is how they implement an animation based on others: https://docs.manim.community/en/stable/_modules/manim/animation/transform.html

**Comment by jeertmans** [comment]
Closing as completed by #285

**Pull request closed without merging**
