### PR TITLE
Fix flake8 check errors: unused imports, tab warning

### PR DESCRIPTION
**Pull request by tdadela**
## Description

Remove unused imports.
Use "noqa W191" to hide  W191 for the REVEALJS_TEMPLATE string.
Maybe it's good idea to move this template to separate file?

I want to say congratulations – great project!

### CODE REVIEW

**Comment by jeertmans** [comment]
Hi @tdadela, many thanks for your contribution and your interest in Manim Slides!

> Maybe it's good idea to move this template to separate file?

Do you mean a separate Python file, or something else? I thank that can be a good idea.

Maybe we should replace all tabs with spaces, and still allow for this warning to occur?

**Comment by tdadela** [comment]
I've moved the template to a separate file.

**Comment by jeertmans** [comment]
Thanks for the update @tdadela!

However, as I was afraid of, you cannot include simply include external files (such as the HTML template) and expect them to be available when installed with pip.

If you were to test `manim-slides convert` in a folder that is not the `manim-slides` repository, this would not work, see the error message:

```console
➜  Desktop manim-slides convert ConvertExample slides.html --open                             
Traceback (most recent call last):
  File "/home/eertmans/.local/bin/manim-slides", line 8, in <module>
    sys.exit(cli())
  File "/home/eertmans/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/eertmans/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/eertmans/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eertmans/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eertmans/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/eertmans/.local/lib/python3.10/site-packages/manim_slides/convert.py", line 202, in convert
    converter.convert_to(dest)
  File "/home/eertmans/.local/lib/python3.10/site-packages/manim_slides/convert.py", line 124, in convert_to
    revealjs_template = self.load_template()
  File "/home/eertmans/.local/lib/python3.10/site-packages/manim_slides/convert.py", line 103, in load_template
    with open(REVEALJS_TEMPLATE_PATH, "r") as content_file:
FileNotFoundError: [Errno 2] No such file or directory: 'manim_slides/revealjs_template.html
```

The solution might be to set up data files, see this [blog post](https://kiwidamien.github.io/making-a-python-package-vi-including-data-files.html).

Do you want to take care or this?

Again, many thanks for your time and for your enthusiasm ;D

**Comment by tdadela** [comment]
>Do you want to take care or this?

Yes
But I'm not sure if I will be doing it next weekend / next month.

**Comment by jeertmans** [comment]
No problem @tdadela! (same for #71)
There is no need to hurry for that, so ping me when you did some work, or if you later decide not to work on this anymore ;-)

**Comment by jeertmans** [comment]
Hi @tdadela, sorry to finally take on this one, but I wanted to move on next features for Manim Slides, and I prefer not to stall issues / PRs for too long ;-)

I hope you don't mind!

**Pull request merged**
