### PR TITLE
Issue more templates

### LINKED ISSUE #42: chore: more issue templates
# What

With #39 and #40, users can now create issues based on template. However, I'd like to have more template, in line to what is done in the [numpy/numpy](https://github.com/numpy/numpy) repository: https://github.com/numpy/numpy/issues/new/choose.

I would love to have templates for
- [ ] Documentation
- [ ] Question/Help/Support

You can get inspiration from the Numpy repository (see above), but I won't be using external links.

# How to

Please, read already existing files in [ISSUE_TEMPLATE](https://github.com/jeertmans/manim-slides/tree/main/.github/ISSUE_TEMPLATE), and get some inspiration from https://github.com/numpy/numpy/issues/new/choose too.

### PR DESCRIPTION
**Pull request by harisaisundhar**
## Description

-  Template drafted for documentation
-  Consists of attributes for describing the issue, link to affected page, Issue type, Recommendation
- Code of conduct is also added, can keep or remove them subjected to approval

## Check List (Check all the applicable boxes)

- [x] I understand that my contributions needs to pass the checks.
- [x] If I created new functions / methods, I documented them and add type hints.
- [ ] If I modified already existing code, I updated the documentation accordingly.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2022-10-19 at 8 13 59 PM

## Note to reviewers

Template for Question/Help/Support is put on hold until further clarification. 

Questions :

1. Should we redirect them to a support page or design a template like the other issues ?
2. If questions based template is to be used, what is the plan to revert back to the user ?

### CODE REVIEW

**Comment by harisaisundhar** [comment]
Closes #42

**Comment by harisaisundhar** [comment]
> Thank you for your work @harisaisundhar! You mention a code a conduct, but I see none: is it normal?

Uh no! I am not aware if we have a document in place. Can remove it otherwise. Also do let me know about the Question/Help/Support, are we planning on raising an issue for that too ?

**Comment by jeertmans** [comment]
@harisaisundhar You can delete the code of conduct section for now, it will be added later if needed :)

You can create a separate PR for the Question/Help/Support template and link to the same issue #42

**Comment by harisaisundhar** [comment]
Sure!

**Comment by harisaisundhar** [comment]
Made the changes. Looks like build is failing from a different issue.

**Comment by jeertmans** [comment]
Don’t worry about pre commit, that’s not a problem :)

thanks for you work! Merging this soon!

**Pull request merged**
