### PR TITLE
fix(convert): Whitespace issue in default RevealJS template

### PR DESCRIPTION
**Pull request by yunusey**
## Description
First of all, thanks for the amazing project!

Recently, I was trying to deploy my animation to web using RevealJS where I wanted the first slide to loop. On the player, everything was working fine, but on the website, the first slide wasn't looping. When I looked at the produced `html` file, I saw this:

```html
...
  <body>
    <div class="reveal">
      <div class="slides"><section
              data-background-size='contain'
              data-background-color="#181926"
              data-background-video="index_assets/{very_long_asset_id}.mp4"
              data-background-video-muteddata-background-video-loop>
              
            </section></div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.1.0/reveal.min.js"></script>
...
```

I think there's a problem with the spacing of `data-background-video-muted` and `data-background-video-loop` [default RevealJS template](https://github.com/jeertmans/manim-slides/blob/main/manim_slides/templates/revealjs.html).

I tested my current change in my slides, it worked fine. I recommend checking out [Jinja2's whitespace control](https://tedboy.github.io/jinja2/templ6.html).

## Check List (Check all the applicable boxes)

- [x] I understand that my contributions needs to pass the checks.
- [x] If I created new functions / methods, I documented them and add type hints.
- [x] If I modified already existing code, I updated the documentation accordingly.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by jeertmans** [comment]
Hello @yunusey, thanks for catching this bug!

I recognize that the "whitespace trimming" performed by Jinja2 is not very consistent in my template, and I definitely should improve it!

Would you mind adding an entry to the CHANGELOG file?

**Comment by jeertmans** [comment]
And thanks for linking to the appropriate documentation, I didn't know about the `trim_blocks` options!

**Comment by yunusey** [comment]
Hi @jeertmans!

I've added the entry ([ddc8394](https://github.com/jeertmans/manim-slides/pull/442/commits/ddc83949e30b87dda78ad0036ed4192d8e855c78)) - I hope you should be able to see it now. I just checked #443, everything looks great. Please let me know if there's anything else I can help with!

**Review by jeertmans — APPROVED** [review]
Thank you, that’s great!

**Pull request merged**
