### PR TITLE
refactor(lib): change PyQT5 to PySide6

### LINKED ISSUE #53: [BUG] manim-slides no longer work on M1 chip
### Description

manim-slides no longer work on M1 chip (or arm64) because of pyqt5. Using Rosetta terminal is not an option.

### Version

v.4.2.0

### Platform

macOS arm64

### Screenshots

_No response_

### Additional information

```
pip install manim-slides==4.2.0
Collecting manim-slides==4.2.0
  Using cached manim-slides-4.2.0.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.62.3 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (4.64.1)
Requirement already satisfied: numpy>=1.19.3 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (1.23.4)
Requirement already satisfied: click>=8.0 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (8.1.3)
Requirement already satisfied: opencv-python>=4.6 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (4.6.0.66)
Collecting pyqt5>=5.15
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

### PR DESCRIPTION
**Pull request by jeertmans**
This, hopefully, should now add support for M1 chips

Closes #53

### CODE REVIEW

**Comment by jeertmans** [comment]
@HadiSDev, you would mind testing by installing this?

`pip install git+https://github.com/jeertmans/manim-slides.git@pyside6`

**Comment by HadiSDev** [comment]
@jeertmans New error :D but closer (Poetry error):
```
 • Installing pyqt5-qt5 (5.15.2): Failed

  RuntimeError

  Unable to find installation candidates for pyqt5-qt5 (5.15.2)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chooser.py:103 in choose_for
       99│ 
      100│             links.append(link)
      101│ 
      102│         if not links:
    → 103│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      104│ 
      105│         # Get the best link
      106│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      107│ 


```

**Comment by HadiSDev** [comment]
It works @jeertmans  :D :D but I am done with the conference so I am not going to use it for a long time xD

**Comment by HadiSDev** [comment]
Well done m8

**Comment by jeertmans** [comment]
No problem @HadiSDev, thanks for testing that :D

**Pull request merged**
